name: 'Cancel this build'
description: 'Uses the GitHub Actions API to cancel the build'
inputs:
  token:
    description: 'Token'
    required: true
  repository:
    description: 'Repository'
    required: true
runs:
  using: 'node12'
  main: 'cancel.js'
branding:
  icon: 'frown'
  color: 'orange'
